In [12]:
import os, sys
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
script_path = os.getcwd()
project_path = os.path.abspath(os.path.join(script_path, '..', '..', '..'))

results_exp_2a_dir = os.path.join(project_path, 'results', 'experiment_2a')
results_exp_2a_path = os.path.join(results_exp_2a_dir, 'master_table_exp_2a.parquet')

results_exp_2b_dir = os.path.join(project_path, 'results', 'experiment_2b')
results_exp_2b_path = os.path.join(results_exp_2b_dir, 'master_table_exp_2b.parquet')

In [14]:
df_results_exp_2a = pl.read_parquet(results_exp_2a_path)
df_results_exp_2b = pl.read_parquet(results_exp_2b_path)

In [15]:
df_results_exp_2a

shape: (25, 37)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ sample_siz ┆ mean_acc ┆ std_acc  ┆ mean_ari ┆ … ┆ imbalance_ ┆ imbalance ┆ is_balanc ┆ convex_ge │
│ e_pct      ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ratio      ┆ _ratio_st ┆ ed        ┆ ometry    │
│ ---        ┆ f64      ┆ f64      ┆ f64      ┆   ┆ ---        ┆ d         ┆ ---       ┆ ---       │
│ f64        ┆          ┆          ┆          ┆   ┆ f64        ┆ ---       ┆ bool      ┆ bool      │
│            ┆          ┆          ┆          ┆   ┆            ┆ f64       ┆           ┆           │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0.5        ┆ 0.83808  ┆ 0.1021   ┆ 0.630713 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 10.0       ┆ 0.860289 ┆ 0.104518 ┆ 0.676921 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 20.0       ┆ 0.854916 ┆ 0.105863 ┆ 0.668114 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 30.0       ┆ 0.855955 ┆ 0.105751 ┆ 0.67099  ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 40.0       ┆ 0.855677 ┆ 0.10576  ┆ 0.669685 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 0.5        ┆ 0.456016 ┆ 0.052925 ┆ 0.06081  ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 10.0       ┆ 0.454028 ┆ 0.056436 ┆ 0.063587 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 20.0       ┆ 0.464605 ┆ 0.054541 ┆ 0.068818 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 30.0       ┆ 0.462598 ┆ 0.055531 ┆ 0.069808 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 40.0       ┆ 0.467098 ┆ 0.056404 ┆ 0.070926 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [16]:
df_results_exp_2b

shape: (15, 37)
┌────────────┬──────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ sample_siz ┆ mean_acc ┆ std_acc  ┆ mean_ari ┆ … ┆ imbalance_ ┆ imbalance ┆ is_balanc ┆ convex_ge │
│ e_pct      ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ratio      ┆ _ratio_st ┆ ed        ┆ ometry    │
│ ---        ┆ f64      ┆ f64      ┆ f64      ┆   ┆ ---        ┆ d         ┆ ---       ┆ ---       │
│ f64        ┆          ┆          ┆          ┆   ┆ f64        ┆ ---       ┆ bool      ┆ bool      │
│            ┆          ┆          ┆          ┆   ┆            ┆ f64       ┆           ┆           │
╞════════════╪══════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0.5        ┆ 0.865534 ┆ 0.069312 ┆ 0.671094 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 10.0       ┆ 0.886914 ┆ 0.022581 ┆ 0.703472 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 20.0       ┆ 0.881992 ┆ 0.02142  ┆ 0.69277  ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 30.0       ┆ 0.881408 ┆ 0.021656 ┆ 0.691731 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 40.0       ┆ 0.879395 ┆ 0.021168 ┆ 0.687349 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ …          ┆ …        ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 0.5        ┆ 0.993726 ┆ 0.012867 ┆ 0.981844 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 10.0       ┆ 0.998409 ┆ 0.000797 ┆ 0.995236 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 20.0       ┆ 0.998712 ┆ 0.000769 ┆ 0.996143 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 30.0       ┆ 0.998787 ┆ 0.0005   ┆ 0.996366 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 40.0       ┆ 0.998832 ┆ 0.000476 ┆ 0.9965   ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
└────────────┴──────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘