In [1]:
import os, sys
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
script_path = os.getcwd()
project_path = os.path.abspath(os.path.join(script_path, '..', '..', '..'))

results_exp_3a_dir = os.path.join(project_path, 'results', 'experiment_3a')
results_exp_3a_path = os.path.join(results_exp_3a_dir, 'master_table_exp_3a.parquet')

results_exp_3b_dir = os.path.join(project_path, 'results', 'experiment_3b')
results_exp_3b_path = os.path.join(results_exp_3b_dir, 'master_table_exp_3b.parquet')

In [3]:
df_results_exp_3a = pl.read_parquet(results_exp_3a_path)
df_results_exp_3b = pl.read_parquet(results_exp_3b_path)

In [4]:
df_results_exp_3a

shape: (27, 38)
┌──────────┬────────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ n_splits ┆ sample_siz ┆ mean_acc ┆ std_acc  ┆ … ┆ imbalance_ ┆ imbalance ┆ is_balanc ┆ convex_ge │
│ ---      ┆ e_pct      ┆ ---      ┆ ---      ┆   ┆ ratio      ┆ _ratio_st ┆ ed        ┆ ometry    │
│ i64      ┆ ---        ┆ f64      ┆ f64      ┆   ┆ ---        ┆ d         ┆ ---       ┆ ---       │
│          ┆ f64        ┆          ┆          ┆   ┆ f64        ┆ ---       ┆ bool      ┆ bool      │
│          ┆            ┆          ┆          ┆   ┆            ┆ f64       ┆           ┆           │
╞══════════╪════════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 3        ┆ 20.0       ┆ 0.8558   ┆ 0.106104 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 3        ┆ 30.0       ┆ 0.850285 ┆ 0.113762 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 3        ┆ 40.0       ┆ 0.854819 ┆ 0.110139 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 5        ┆ 20.0       ┆ 0.854105 ┆ 0.107569 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 5        ┆ 30.0       ┆ 0.852857 ┆ 0.106398 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ …        ┆ …          ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 5        ┆ 30.0       ┆ 0.992895 ┆ 0.010125 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 5        ┆ 40.0       ┆ 0.993329 ┆ 0.009441 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 10       ┆ 20.0       ┆ 0.990214 ┆ 0.011956 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 10       ┆ 30.0       ┆ 0.990122 ┆ 0.013776 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 10       ┆ 40.0       ┆ 0.992027 ┆ 0.010762 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
└──────────┴────────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [5]:
df_results_exp_3b

shape: (18, 38)
┌──────────┬────────────┬──────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ n_splits ┆ sample_siz ┆ mean_acc ┆ std_acc  ┆ … ┆ imbalance_ ┆ imbalance ┆ is_balanc ┆ convex_ge │
│ ---      ┆ e_pct      ┆ ---      ┆ ---      ┆   ┆ ratio      ┆ _ratio_st ┆ ed        ┆ ometry    │
│ i64      ┆ ---        ┆ f64      ┆ f64      ┆   ┆ ---        ┆ d         ┆ ---       ┆ ---       │
│          ┆ f64        ┆          ┆          ┆   ┆ f64        ┆ ---       ┆ bool      ┆ bool      │
│          ┆            ┆          ┆          ┆   ┆            ┆ f64       ┆           ┆           │
╞══════════╪════════════╪══════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 3        ┆ 20.0       ┆ 0.889775 ┆ 0.015109 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 3        ┆ 30.0       ┆ 0.887796 ┆ 0.011809 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 3        ┆ 40.0       ┆ 0.886704 ┆ 0.012429 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 5        ┆ 20.0       ┆ 0.885882 ┆ 0.018375 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ 5        ┆ 30.0       ┆ 0.88951  ┆ 0.011161 ┆ … ┆ 1.0003     ┆ 0.0       ┆ true      ┆ true      │
│ …        ┆ …          ┆ …        ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 5        ┆ 30.0       ┆ 0.873169 ┆ 0.009683 ┆ … ┆ 1.0001     ┆ 0.0       ┆ true      ┆ true      │
│ 5        ┆ 40.0       ┆ 0.870567 ┆ 0.009043 ┆ … ┆ 1.0001     ┆ 0.0       ┆ true      ┆ true      │
│ 10       ┆ 20.0       ┆ 0.885759 ┆ 0.008354 ┆ … ┆ 1.0001     ┆ 0.0       ┆ true      ┆ true      │
│ 10       ┆ 30.0       ┆ 0.881419 ┆ 0.007871 ┆ … ┆ 1.0001     ┆ 0.0       ┆ true      ┆ true      │
│ 10       ┆ 40.0       ┆ 0.879022 ┆ 0.006682 ┆ … ┆ 1.0001     ┆ 0.0       ┆ true      ┆ true      │
└──────────┴────────────┴──────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘